### PR TITLE
add text4.txt

### PR DESCRIPTION
**Pull request by BuiVannn**

### CODE REVIEW

**Review by TINABJan254 — DISMISSED** [review]
Sửa nội dung

**Review by TINABJan254 — APPROVED** [review]
Approve

**Comment by duongvu5** [comment]
@PTIT-D22KH/btn_java_24-25t1_nmson

**Review by duongvu5 — APPROVED** [review]
okay

**Review by duongvu4 — APPROVED** [review]
okay!!

**Review by vucongtuanduong — APPROVED** [review]
okay!!!

**Pull request merged**
