### PR TITLE
Them test3.txt

### PR DESCRIPTION
**Pull request by vucongtuanduong**

### CODE REVIEW

**Review by TINABJan254 — COMMENTED** [review]
Ok

**Review by TINABJan254 — CHANGES_REQUESTED** [review]
Thêm nội dung file

**Review by BuiVannn — COMMENTED** [review]
ok

**Review by BuiVannn — APPROVED** [review]

**Review by TINABJan254 — APPROVED** [review]
Approve

**Review by duongvu5 — APPROVED** [review]
okay

**Review by duongvu4 — APPROVED** [review]
okay!!!

**Pull request merged**
